### ISSUE TITLE
勘误：计网实验以及探索

### ISSUE THREAD

**Issue by Mythologyli** [Phil-Fan/Notebook#3]
## 4.2 反向代理

[Mythologyli/zju-connect: ZJU RVPN 客户端的 Go 语言实现](https://github.com/Mythologyli/ZJU-Connect)

**zju-connect 是一个 VPN，显然是一个正向代理 (Forward Proxy)。学校给 EasyConnect 的命名 RVPN 容易引起误导**

**Comment by Phil-Fan** [comment]
感谢勘误~ :smile:
